In [1]:
import os
import numpy as np
import itertools, operator, os
import matplotlib.pyplot as plt
# CORPUS_PATH = os.path.join('data/', 'ClassifiedTweet_sample')
CORPUS_PATH = os.path.join('/Users/koitaroh/Documents/Data/Tweet/', 'ClassifiedTweet_20150709')
filenames = sorted([os.path.join(CORPUS_PATH, fn) for fn in os.listdir(CORPUS_PATH)])

In [2]:
len(filenames)

1484214

In [3]:
def grouper(n, iterable, fillvalue=None):
    "Collect data into fixed-length chunks or blocks"
    args = [iter(iterable)] * n
    return itertools.zip_longest(*args, fillvalue=fillvalue)

In [4]:
doctopic_triples = []
mallet_docnames = []

In [5]:
# with open("/Users/koitaroh/Documents/GitHub/GeoTweetCollector/data/doc-topics-tweet.txt", encoding="utf-8") as f:
with open("/Users/koitaroh/Documents/GitHub/GeoTweetCollector/data/doc-topics-tweet-20150709.txt", encoding="utf-8") as f:
    f.readline()  # read one line in order to skip the header
    
    for line in f:
        docnum, docname, *values = line.rstrip().split('\t')
        
        mallet_docnames.append(docname)
        for topic, share in grouper(2, values):
            triple = (docname, int(topic), float(share))
            doctopic_triples.append(triple)
            
# sort the triples
# triple is (docname, topicnum, share) so sort(key=operator.itemgetter(0,1))
# sorts on (docname, topicnum) which is what we want

In [7]:
doctopic_triples = sorted(doctopic_triples, key=operator.itemgetter(0,1))
mallet_docnames = sorted(mallet_docnames)

In [8]:
mallet_docnames[:10]

['file:/Users/koitaroh/Documents/Data/Tweet/ClassifiedTweet_20150709/2015031714_12147_3122.txt',
 'file:/Users/koitaroh/Documents/Data/Tweet/ClassifiedTweet_20150709/2015031714_12408_2433.txt',
 'file:/Users/koitaroh/Documents/Data/Tweet/ClassifiedTweet_20150709/2015031714_12414_2434.txt',
 'file:/Users/koitaroh/Documents/Data/Tweet/ClassifiedTweet_20150709/2015031714_12422_2435.txt',
 'file:/Users/koitaroh/Documents/Data/Tweet/ClassifiedTweet_20150709/2015031714_12644_3745.txt',
 'file:/Users/koitaroh/Documents/Data/Tweet/ClassifiedTweet_20150709/2015031714_12645_3745.txt',
 'file:/Users/koitaroh/Documents/Data/Tweet/ClassifiedTweet_20150709/2015031714_12680_3756.txt',
 'file:/Users/koitaroh/Documents/Data/Tweet/ClassifiedTweet_20150709/2015031714_12694_3755.txt',
 'file:/Users/koitaroh/Documents/Data/Tweet/ClassifiedTweet_20150709/2015031714_12698_3756.txt',
 'file:/Users/koitaroh/Documents/Data/Tweet/ClassifiedTweet_20150709/2015031714_12700_3757.txt']

In [9]:
num_docs = len(mallet_docnames)
num_docs

1484214

In [10]:
len(doctopic_triples)

29684280

In [11]:
num_topics = len(doctopic_triples) // len(mallet_docnames)
num_topics

20

In [12]:
doctopic = np.zeros((num_docs, num_topics))

In [13]:
i = 0
for triple in doctopic_triples:
    docname, topic, share = triple
    j = i//num_topics
    # row_num = mallet_docnames.index(docname)
    doctopic[j, topic] = share
    i += 1

In [14]:
doctopic[:5]

array([[ 0.03676471,  0.03676471,  0.06617647,  0.03676471,  0.03676471,
         0.03676471,  0.05147059,  0.08088235,  0.06617647,  0.03676471,
         0.03676471,  0.08088235,  0.05147059,  0.03676471,  0.08088235,
         0.03676471,  0.05147059,  0.05147059,  0.03676471,  0.05147059],
       [ 0.04545455,  0.04545455,  0.04545455,  0.04545455,  0.04545455,
         0.04545455,  0.04545455,  0.04545455,  0.04545455,  0.04545455,
         0.04545455,  0.04545455,  0.06363636,  0.04545455,  0.06363636,
         0.04545455,  0.08181818,  0.06363636,  0.04545455,  0.04545455],
       [ 0.04807692,  0.06730769,  0.04807692,  0.04807692,  0.04807692,
         0.04807692,  0.04807692,  0.04807692,  0.04807692,  0.04807692,
         0.04807692,  0.04807692,  0.04807692,  0.04807692,  0.06730769,
         0.04807692,  0.04807692,  0.04807692,  0.04807692,  0.04807692],
       [ 0.04166667,  0.04166667,  0.09166667,  0.04166667,  0.04166667,
         0.075     ,  0.04166667,  0.04166667,  

In [15]:
unit_names = []

In [16]:
# Scenario 11 total tempo / total spatio
# Scenario 12 days / total spatio
# Scenario 13 hours / total spatio

for fn in filenames:
    basename = os.path.basename(fn)
    name, ext = os.path.splitext(basename)
    name = name.rstrip('0123456789')
    name = name.rstrip('-')
    name = name.rstrip('_')
    name = name.rstrip('0123456789')
    name = name.rstrip('-')
    name = name.rstrip('_')
    unit_names.append(name)

In [17]:
unit_names = np.asarray(unit_names)
doctopic_orig = doctopic.copy()
num_groups = len(set(unit_names))
doctopic_grouped = np.zeros((num_groups, num_topics))
for i, name in enumerate(sorted(set(unit_names))):
    doctopic_grouped[i, :] = np.mean(doctopic[unit_names == name, :], axis=0)
doctopic = doctopic_grouped

In [18]:
doctopic[:5]

array([[ 0.04980463,  0.05209209,  0.04874867,  0.04966302,  0.04986556,
         0.0503426 ,  0.04967995,  0.05109752,  0.04906836,  0.05073749,
         0.04866086,  0.05117176,  0.05009829,  0.04943591,  0.04974578,
         0.05070518,  0.0492259 ,  0.05051576,  0.04865292,  0.05068774]])

In [5]:
#inspecting the result
from sklearn.feature_extraction.text import CountVectorizer
# CORPUS_PATH_UNSPLIT = os.path.join('data/', 'ClassifiedTweet_sample')
CORPUS_PATH_UNSPLIT = os.path.join('/Users/koitaroh/Documents/Data/Tweet/', 'ClassifiedTweet_20150709')

In [6]:
filenames = [os.path.join(CORPUS_PATH_UNSPLIT, fn) for fn in sorted(os.listdir(CORPUS_PATH_UNSPLIT))]

In [7]:
vectorizer = CountVectorizer(input='filename')

In [8]:
dtm = vectorizer.fit_transform(filenames)  # a sparse matrix

In [9]:
dtm.shape

(1484214, 466392)

In [10]:
dtm.data.nbytes  # number of bytes dtm takes up

167866384

In [ ]:
dtm.toarray().data.nbytes  # number of bytes dtm as array takes up

In [27]:
doctopic_orig.shape

(70, 20)

In [28]:
doctopic_orig.data.nbytes  # number of bytes document-topic shares take up

11200

In [29]:
novels = sorted(set(unit_names))

In [30]:
print("Top topics in...")
for i in range(len(doctopic)):
    top_topics = np.argsort(doctopic[i,:])[::-1][0:3]
    top_topics_str = ' '.join(str(t) for t in top_topics)
    print("{}: {}".format(novels[i], top_topics_str))

Top topics in...
2015031714: 1 11 7


In [33]:
with open('/Users/koitaroh/Documents/GitHub/GeoTweetCollector/data/topic-keys-tweet-20150714.txt', encoding="utf-8") as input:
# with open('/Users/koitaroh/Documents/GitHub/GeoTweetCollector/data/topic-keys-tweet.txt', encoding="utf-8") as input:
    topic_keys_lines = input.readlines()

In [34]:
topic_words = []

In [35]:
for line in topic_keys_lines:
    _, _, words = line.split('\t')  # tab-separated
    words = words.rstrip().split(' ')  # remove the trailing '\n'
    topic_words.append(words)

In [36]:
topic_words[0]

['ん',
 'ます',
 '歌',
 'ちゃ',
 'きえ',
 '買いもの',
 '算数',
 'なんか',
 '彫',
 'まさに',
 'ρ',
 '所',
 'タイヤ',
 'o',
 'やっと',
 'あ',
 'パークスビジョン',
 'こんな',
 'すぎる']

In [38]:
N_WORDS_DISPLAY = 10
for t in range(len(topic_words)):
    print("Topic {}: {}".format(t, ' '.join(topic_words[t][:N_WORDS_DISPLAY])))

Topic 0: ん ます 歌 ちゃ きえ 買いもの 算数 なんか 彫 まさに
Topic 1: た お する とき 春 ちゃん lan 仙台 良かっ 終了
Topic 2: in 入っ イングリッシュ 食べる ゝ 使い 落ち着く はご バイト こ
Topic 3: な って なる じゃあ wi ラップ 解ける 有線 麗らか 違う
Topic 4: こと 今 だる 市 itmedia 抜き差し wwwww みんな 小 年
Topic 5: か わ 栃木 バッグ スト ブロック ば 宿題 最近 青
Topic 6: 笑 入れ 豆腐 公衆 刺す 番 思わず s 回線 やすい
Topic 7: ー よ ﾟ 小学生 長浜 まし 中 無線 でぶ ツイート
Topic 8: 今日 好き sendai 問題 台場 過ぎ おっ カスタム それだけ 軽く
Topic 9: なっ 気 キムチ 本日 成長 狩り 帝釈天 柴又 勿論 爆笑
Topic 10: おもろい 笑 fi なかっ ありがと やつ 付近 少し ホイール じん
Topic 11: て き じゃ もっ あんまり 狼 流行っ 一 あと 体
Topic 12: だ いい ω 受付 店員 きん 娘 σ 東京 い
Topic 13: ね ん 人 夢中 進ん 県境 都 やる 眩しい ねぇ
Topic 14: 変え 作っ でる mobile free ぼく う 薄着 可愛く 切れ
Topic 15: た さん うどん できる ーツイート 難しかっ takuya 年中 群馬 駅
Topic 16: けど ️ いき ちゃっ 初 ก 死刑 うらやま めちゃくちゃ 長野
Topic 17: ない てか 剣 ︎ てる わら や 今週 うち たのしん
Topic 18: なう ありがとう いえ サービス 無料 時 あちこち 永山 乗っ 言う
Topic 19: 県 部屋 暑い たら だろ とく 匂い さ いちご ヒョエエエエエエ


In [18]:
# Visualizing the result as bar chart
N, K = doctopic.shape
ind = np.arange(N)  # points on the x-axis
width = 0.5

In [19]:
plt.bar(ind, doctopic[:,0], width=width)

<Container object of 239 artists>

In [20]:
unit_names

array(['2015031714', '2015031714', '2015031714', ..., '2015032712',
       '2015032712', '2015032712'], 
      dtype='<U10')

In [21]:
plt.xticks(ind + width/2, unit_names)  # put labels in the center

([<matplotlib.axis.XTick at 0x1cf67ddd8>,
 <a list of 239 Text xticklabel objects>)

In [22]:
plt.title('Share of Topic #0')
plt.show()

In [23]:
# Stacked chart
N, K = doctopic.shape  # N documents, K topics
ind = np.arange(N)  # the x-axis locations for the novels
width = 0.5  # the width of the bars
plots = []
height_cumulative = np.zeros(N)

for k in range(K):
    color = plt.cm.coolwarm(k/K, 1)
    if k == 0:
        p = plt.bar(ind, doctopic[:, k], width, color=color)
    else:
        p = plt.bar(ind, doctopic[:, k], width, bottom=height_cumulative, color=color)
    height_cumulative += doctopic[:, k]
    plots.append(p)

In [24]:
plt.ylim((0, 1))  # proportions sum to 1, so the height of the stacked bars is 1

(0, 1)

In [25]:
plt.ylabel('Topics')

In [26]:
plt.title('Topics in novels')

In [27]:
plt.xticks(ind+width/2, unit_names)

([<matplotlib.axis.XTick at 0x1cc683710>,
 <a list of 239 Text xticklabel objects>)

In [28]:
plt.yticks(np.arange(0, 1, 10))

([<matplotlib.axis.YTick at 0x1cf676198>],
 <a list of 1 Text yticklabel objects>)

In [29]:
topic_labels = ['Topic #{}'.format(k) for k in range(K)]

In [30]:
plt.legend([p[0] for p in plots], topic_labels)
plt.show()

In [31]:
# Heat map
# Ref: http://nbviewer.ipython.org/5427209
# Ref: http://code.activestate.com/recipes/578175-hierarchical-clustering-heatmap-python/
plt.pcolor(doctopic, norm=None, cmap='Blues')

In [32]:
# put the major ticks at the middle of each cell
# the trailing semicolon ';' suppresses output
plt.yticks(np.arange(doctopic.shape[0])+0.5, unit_names);

In [33]:
plt.xticks(np.arange(doctopic.shape[1])+0.5, topic_labels);

In [34]:
# flip the y-axis so the texts are in the order we anticipate (Austen first, then Brontë)
plt.gca().invert_yaxis()

In [35]:
# rotate the ticks on the x-axis
plt.xticks(rotation=90)

(array([  0.5,   1.5,   2.5,   3.5,   4.5,   5.5,   6.5,   7.5,   8.5,
          9.5,  10.5,  11.5,  12.5,  13.5,  14.5,  15.5,  16.5,  17.5,
         18.5,  19.5]), <a list of 20 Text xticklabel objects>)

In [36]:
# add a legend
plt.colorbar(cmap='Blues')

In [37]:
plt.tight_layout()  # fixes margins

/usr/local/lib/python3.4/site-packages/matplotlib/tight_layout.py:225: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")


In [ ]:
plt.show()